freebirds sys handover
simplybusiness/flip_fab pull request #46
Opened 2022-11-10 19:25 UTC by petertimwalker

2022-11-11 19:51 UTC, petertimwalker commented on spec/lib/flip_fab/cookie_persistence_spec.rb
> +      before { Timecop.freeze(Time.utc(1990)) }
This is so local tests work when in a different timezone

2022-11-11 19:52 UTC, petertimwalker commented on .semaphore/semaphore.yml
> +          value: 3.0.4
I figured the semaphore builds should be using the same ruby version as described in .ruby-version

2022-11-11 20:01 UTC, dominicarmitage-sb requested changes
I'm concerned by removing that method we are potentially breaking code that uses this lib ie Chopin

2022-11-15 14:12 UTC, dominicarmitage-sb approved these changes

2022-11-15 14:13 UTC, merged